name: Create Jira issue from labeled PR

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  call-create-jira:
    if: github.event.label.name == 'create-jira'
    uses: Personal-Testing-Organization/.github/.github/workflows/create-jira-from-pr.yml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
